title: TACRED Relation Extraction
author: Xinyu Guo
description: Sentence-pair classification for relation extraction on the TACRED dataset.
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      css: "/assets/css/style.scss"
